/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSlugRouteImport } from './routes/subject.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassroomRouteImport } from './routes/_authenticated/classroom'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedClassroomIndexRouteImport } from './routes/_authenticated/classroom.index'
import { Route as AuthenticatedAssistantIndexRouteImport } from './routes/_authenticated/assistant.index'
import { Route as TitleTypeIdRouteImport } from './routes/title.$type.$id'
import { Route as ApiPublicMongoDiagRouteImport } from './routes/api/public/mongo-diag'
import { Route as AuthenticatedClassroomClassIdRouteImport } from './routes/_authenticated/classroom.$classId'
import { Route as AuthenticatedAssistantThreadIdRouteImport } from './routes/_authenticated/assistant.$threadId'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSlugRoute = SubjectSlugRouteImport.update({
  id: '/subject/$slug',
  path: '/subject/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassroomRoute = AuthenticatedClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassroomIndexRoute =
  AuthenticatedClassroomIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const AuthenticatedAssistantIndexRoute =
  AuthenticatedAssistantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)
const TitleTypeIdRoute = TitleTypeIdRouteImport.update({
  id: '/title/$type/$id',
  path: '/title/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMongoDiagRoute = ApiPublicMongoDiagRouteImport.update({
  id: '/api/public/mongo-diag',
  path: '/api/public/mongo-diag',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClassroomClassIdRoute =
  AuthenticatedClassroomClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedClassroomRoute,
  } as any)
const AuthenticatedAssistantThreadIdRoute =
  AuthenticatedAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/classroom': typeof AuthenticatedClassroomRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/subject/$slug': typeof SubjectSlugRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/api/public/mongo-diag': typeof ApiPublicMongoDiagRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/classroom/': typeof AuthenticatedClassroomIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/subject/$slug': typeof SubjectSlugRoute
  '/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/api/public/mongo-diag': typeof ApiPublicMongoDiagRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/assistant': typeof AuthenticatedAssistantIndexRoute
  '/classroom': typeof AuthenticatedClassroomIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subjects': typeof SubjectsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRouteWithChildren
  '/_authenticated/classroom': typeof AuthenticatedClassroomRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/subject/$slug': typeof SubjectSlugRoute
  '/_authenticated/assistant/$threadId': typeof AuthenticatedAssistantThreadIdRoute
  '/_authenticated/classroom/$classId': typeof AuthenticatedClassroomClassIdRoute
  '/api/public/mongo-diag': typeof ApiPublicMongoDiagRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/_authenticated/assistant/': typeof AuthenticatedAssistantIndexRoute
  '/_authenticated/classroom/': typeof AuthenticatedClassroomIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/subjects'
    | '/admin'
    | '/assistant'
    | '/classroom'
    | '/dashboard'
    | '/api/chat'
    | '/subject/$slug'
    | '/assistant/$threadId'
    | '/classroom/$classId'
    | '/api/public/mongo-diag'
    | '/title/$type/$id'
    | '/assistant/'
    | '/classroom/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/subjects'
    | '/admin'
    | '/dashboard'
    | '/api/chat'
    | '/subject/$slug'
    | '/assistant/$threadId'
    | '/classroom/$classId'
    | '/api/public/mongo-diag'
    | '/title/$type/$id'
    | '/assistant'
    | '/classroom'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/subjects'
    | '/_authenticated/admin'
    | '/_authenticated/assistant'
    | '/_authenticated/classroom'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/subject/$slug'
    | '/_authenticated/assistant/$threadId'
    | '/_authenticated/classroom/$classId'
    | '/api/public/mongo-diag'
    | '/title/$type/$id'
    | '/_authenticated/assistant/'
    | '/_authenticated/classroom/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubjectsRoute: typeof SubjectsRoute
  ApiChatRoute: typeof ApiChatRoute
  SubjectSlugRoute: typeof SubjectSlugRoute
  ApiPublicMongoDiagRoute: typeof ApiPublicMongoDiagRoute
  TitleTypeIdRoute: typeof TitleTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$slug': {
      id: '/subject/$slug'
      path: '/subject/$slug'
      fullPath: '/subject/$slug'
      preLoaderRoute: typeof SubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classroom': {
      id: '/_authenticated/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof AuthenticatedClassroomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classroom/': {
      id: '/_authenticated/classroom/'
      path: '/'
      fullPath: '/classroom/'
      preLoaderRoute: typeof AuthenticatedClassroomIndexRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/_authenticated/assistant/': {
      id: '/_authenticated/assistant/'
      path: '/'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthenticatedAssistantIndexRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
    '/title/$type/$id': {
      id: '/title/$type/$id'
      path: '/title/$type/$id'
      fullPath: '/title/$type/$id'
      preLoaderRoute: typeof TitleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mongo-diag': {
      id: '/api/public/mongo-diag'
      path: '/api/public/mongo-diag'
      fullPath: '/api/public/mongo-diag'
      preLoaderRoute: typeof ApiPublicMongoDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/classroom/$classId': {
      id: '/_authenticated/classroom/$classId'
      path: '/$classId'
      fullPath: '/classroom/$classId'
      preLoaderRoute: typeof AuthenticatedClassroomClassIdRouteImport
      parentRoute: typeof AuthenticatedClassroomRoute
    }
    '/_authenticated/assistant/$threadId': {
      id: '/_authenticated/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAssistantRoute
    }
  }
}

interface AuthenticatedAssistantRouteChildren {
  AuthenticatedAssistantThreadIdRoute: typeof AuthenticatedAssistantThreadIdRoute
  AuthenticatedAssistantIndexRoute: typeof AuthenticatedAssistantIndexRoute
}

const AuthenticatedAssistantRouteChildren: AuthenticatedAssistantRouteChildren =
  {
    AuthenticatedAssistantThreadIdRoute: AuthenticatedAssistantThreadIdRoute,
    AuthenticatedAssistantIndexRoute: AuthenticatedAssistantIndexRoute,
  }

const AuthenticatedAssistantRouteWithChildren =
  AuthenticatedAssistantRoute._addFileChildren(
    AuthenticatedAssistantRouteChildren,
  )

interface AuthenticatedClassroomRouteChildren {
  AuthenticatedClassroomClassIdRoute: typeof AuthenticatedClassroomClassIdRoute
  AuthenticatedClassroomIndexRoute: typeof AuthenticatedClassroomIndexRoute
}

const AuthenticatedClassroomRouteChildren: AuthenticatedClassroomRouteChildren =
  {
    AuthenticatedClassroomClassIdRoute: AuthenticatedClassroomClassIdRoute,
    AuthenticatedClassroomIndexRoute: AuthenticatedClassroomIndexRoute,
  }

const AuthenticatedClassroomRouteWithChildren =
  AuthenticatedClassroomRoute._addFileChildren(
    AuthenticatedClassroomRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRouteWithChildren
  AuthenticatedClassroomRoute: typeof AuthenticatedClassroomRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRouteWithChildren,
  AuthenticatedClassroomRoute: AuthenticatedClassroomRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubjectsRoute: SubjectsRoute,
  ApiChatRoute: ApiChatRoute,
  SubjectSlugRoute: SubjectSlugRoute,
  ApiPublicMongoDiagRoute: ApiPublicMongoDiagRoute,
  TitleTypeIdRoute: TitleTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
